name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-nextest
      uses: taiki-e/install-action@cargo-nextest

    - uses: Swatinem/rust-cache@v2

    - name: Run Clippy
      run: cargo clippy --all-targets -- -D warnings

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Run Tests
      run: cargo nextest run
